version: '3.7'
services:

  app:
    build: .
    command: ["yarn", "run", "dev"]
    volumes:
      - /home/node/app/node_modules
      - .:/home/node/app
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/bin/docker

  redis:
    image: redis:4.0.5-alpine
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data

volumes:
  redis-data: